### ISSUE TITLE
상세페이지에서 모달 띄울 시 제목이 뜨는 현상

### ISSUE THREAD

**Issue by hyeyoon** [pm0603/frontend-pm0603#3]
상세 페이지에서 모달창을 띄웠을 때 제목이 모달보다 상위에 뜨는 오류가 있습니다. 

![detail_page](https://cloud.githubusercontent.com/assets/13035393/24834848/677b9b0a-1d2b-11e7-861c-df4996deb83c.png)

**Comment by csparkzxc1** [comment]
![2017-04-11 8 23 31](https://cloud.githubusercontent.com/assets/24959129/24907909/189558c6-1ef9-11e7-8acd-ca50f4d71826.png)
z-index 삭제해서 해결했습니다!
